# SConscript for Nonpareil
# $Id$
# Copyright 2004, 2005 Eric L. Smith <eric@brouhaha.com>

# Nonpareil is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.  Note that I am not
# granting permission to redistribute or modify Nonpareil under the
# terms of any later version of the General Public License.

# Nonpareil is distributed in the hope that they will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program (in the file "COPYING"); if not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111, USA.

Import('env source_release_dir snapshot_dir')

#-----------------------------------------------------------------------------
# Install KML files
#-----------------------------------------------------------------------------

kmls = Split ("""35.kml 45.kml 55.kml 80.kml
                 21.kml 25.kml
                 67.kml
                 32e.kml 33c.kml 34c.kml 37e.kml 38c.kml 38e.kml
                 41cv.kml 41cx.kml
                 11c.kml 12c.kml 15c.kml 16c.kml""")

env.Alias (target = 'install',
           source = env.Install (dir = env ['destdir'] + env ['libdir'],
                                 source = kmls))

#-----------------------------------------------------------------------------
# source tarball
#-----------------------------------------------------------------------------

dist_files = ['SConscript'] + kmls

env.Distribute (source_release_dir, dist_files)
                
env.Distribute (snapshot_dir, dist_files)
