# SConscript for Nonpareil
# $Id$
# Copyright 2004 Eric L. Smith <eric@brouhaha.com>

# Nonpareil is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.  Note that I am not
# granting permission to redistribute or modify Nonpareil under the
# terms of any later version of the General Public License.

# Nonpareil is distributed in the hope that they will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program (in the file "COPYING"); if not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111, USA.

Import('env source_release_dir')

#-----------------------------------------------------------------------------
# Install KML files
#-----------------------------------------------------------------------------

kmls = Split ("""hp35.kml hp45.kml hp55.kml hp80.kml
                 hp21.kml hp25.kml
                 hp67.kml
                 hp32e.kml hp33c.kml hp34c.kml hp37e.kml hp38c.kml hp38e.kml
                 hp41cv.kml
                 hp16c.kml""")

env.Alias (target = 'install',
           source = env.Install (dir = env ['prefix'] + "/lib/nonpareil",
                                 source = kmls))

#-----------------------------------------------------------------------------
# source tarball
#-----------------------------------------------------------------------------

env.Distribute (source_release_dir,
                ['SConscript'] + kmls)
