# SConscript for Nonpareil
# $Id$
# Copyright 2005, 2008 Eric Smith <eric@brouhaha.com>

# Nonpareil is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.  Note that I am not
# granting permission to redistribute or modify Nonpareil under the
# terms of any later version of the General Public License.

# Nonpareil is distributed in the hope that they will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program (in the file "COPYING"); if not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111, USA.

Import('env')

#-----------------------------------------------------------------------------
# SCons builders
#-----------------------------------------------------------------------------

licenses = Split ("""GPL-2.txt GPL-3.0.txt CC-BY-NC-ND-3.0.txt CC-BY-SA-3.0.txt""")


#-----------------------------------------------------------------------------
# source tarball
#-----------------------------------------------------------------------------

dist_files = ['SConscript'] + licenses

env.Tarball (env ['source_release_tarball'], dist_files)
env.Tarball (env ['source_snapshot_tarball'], dist_files)
