# Nonpareil
# Copyright 2022 Eric smith <spacewar@gmail.com>

Import('env')

ncd_names = ['16c']
rom_names = ['16c']

ncd_template_files = [env.File(nn + '.ncd.tmpl') for nn in ncd_names]

rom_files = [env.File(rom_name + '.rom') for rom_name in rom_names]

ncd_files = [env.NCD(target = nn)[0] for nn in ncd_names]

Return('ncd_files')
