# Nonpareil
# Copyright 2022 Eric SMith <spacewar@gmail.com>

Import('env')

ncd_names = ['41c', '41cv', '41cx']

rom_names = ['41-gff',
	     '41-nfldcc']

ncd_template_files = [env.File(nn + '.ncd.tmpl') for nn in ncd_names]

rom_files = [env.File(rom_name + '.rom') for rom_name in rom_names]

ncd_files = [env.NCD(target = nn)[0] for nn in ncd_names]

dist_files = rom_files + ncd_template_files
env.Tarball(env['source_release_tarball'], dist_files)
env.Tarball(env['source_snapshot_tarball'], dist_files)

Return('ncd_files')

