# SConscript for Nonpareil
# $Id$
# Copyright 2004 Eric L. Smith <eric@brouhaha.com>

# Nonpareil is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.  Note that I am not
# granting permission to redistribute or modify Nonpareil under the
# terms of any later version of the General Public License.

# Nonpareil is distributed in the hope that they will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program (in the file "COPYING"); if not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111, USA.

Import('env')
Import('release')

#-----------------------------------------------------------------------------
# Install image files
#-----------------------------------------------------------------------------

images = Split ("""hp35.png hp45.png hp55.png hp80.png
	           hp25.png
                   hp32e.png hp33c.png hp34c.png hp37e.png hp38c.png
                   hp41cv.png
                   hp16c.png""")

env.Alias (target = 'install',
           source = env.Install (dir = env ['prefix'] + "/lib/nonpareil",
                                 source = images))

#-----------------------------------------------------------------------------
# source tarball
#-----------------------------------------------------------------------------

env.Distribute ('nonpareil-' + release,
                images)
